/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HoosatAddress = IDL.Text;
export const WalletAddress = IDL.Record({
  'principal' : IDL.Principal,
  'hoosatAddress' : HoosatAddress,
});
export const Contact = IDL.Record({
  'displayName' : IDL.Text,
  'address' : HoosatAddress,
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func([HoosatAddress, HoosatAddress, IDL.Text], [], []),
  'getAllWalletAddresses' : IDL.Func([], [IDL.Vec(WalletAddress)], ['query']),
  'getContacts' : IDL.Func([HoosatAddress], [IDL.Vec(Contact)], ['query']),
  'getWalletAddress' : IDL.Func([IDL.Principal], [HoosatAddress], ['query']),
  'registerWalletAddress' : IDL.Func([HoosatAddress], [], []),
  'removeContact' : IDL.Func([HoosatAddress, HoosatAddress], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HoosatAddress = IDL.Text;
  const WalletAddress = IDL.Record({
    'principal' : IDL.Principal,
    'hoosatAddress' : HoosatAddress,
  });
  const Contact = IDL.Record({
    'displayName' : IDL.Text,
    'address' : HoosatAddress,
  });
  
  return IDL.Service({
    'addContact' : IDL.Func([HoosatAddress, HoosatAddress, IDL.Text], [], []),
    'getAllWalletAddresses' : IDL.Func([], [IDL.Vec(WalletAddress)], ['query']),
    'getContacts' : IDL.Func([HoosatAddress], [IDL.Vec(Contact)], ['query']),
    'getWalletAddress' : IDL.Func([IDL.Principal], [HoosatAddress], ['query']),
    'registerWalletAddress' : IDL.Func([HoosatAddress], [], []),
    'removeContact' : IDL.Func([HoosatAddress, HoosatAddress], [], []),
  });
};

export const init = ({ IDL }) => { return []; };