/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact { 'displayName' : string, 'address' : HoosatAddress }
export type HoosatAddress = string;
export interface FileMetadata { 'fileName' : string, 'fileSize' : bigint, 'fileType' : string }
export type MessageType = { 'text' : null } | { 'file' : null } | { 'voice' : null };
export interface Message {
  'sender' : HoosatAddress,
  'recipient' : HoosatAddress,
  'content' : string,
  'timestamp' : bigint,
  'messageType' : MessageType,
  'fileMetadata' : [] | [FileMetadata],
}
export interface WalletAddress {
  'principal' : Principal,
  'hoosatAddress' : HoosatAddress,
}
export interface _SERVICE {
  'addContact' : ActorMethod<[HoosatAddress, HoosatAddress, string], undefined>,
  'getAllWalletAddresses' : ActorMethod<[], Array<WalletAddress>>,
  'getContacts' : ActorMethod<[HoosatAddress], Array<Contact>>,
  'getMessages' : ActorMethod<[HoosatAddress, HoosatAddress], Array<Message>>,
  'getWalletAddress' : ActorMethod<[Principal], HoosatAddress>,
  'registerWalletAddress' : ActorMethod<[HoosatAddress], undefined>,
  'removeContact' : ActorMethod<[HoosatAddress, HoosatAddress], undefined>,
  'sendMessage' : ActorMethod<[HoosatAddress, HoosatAddress, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
